#!/usr/bin/env bash
# Emit EtRuntimePin.cmake (contract C6) to stdout.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/lib/naming.sh"

VERSION=""; ETVER=""; BASEURL=""; ROWS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --etver) ETVER="$2"; shift 2 ;;
    --base-url) BASEURL="$2"; shift 2 ;;
    --row) ROWS+=("$2 $3 $4"); shift 4 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
: "${VERSION:?}"; : "${ETVER:?}"; : "${BASEURL:?}"

printf '# Generated by executorch-runtime-dist release v%s. Do not edit by hand.\n' "$VERSION"
printf 'set(ET_RUNTIME_VERSION "%s")\n' "$VERSION"
printf 'set(ET_RUNTIME_ET_VERSION "%s")\n\n' "$ETVER"
for r in "${ROWS[@]}"; do
  # shellcheck disable=SC2086  # split the "variant platform sha" triple
  set -- $r
  variant="$1"; platform="$2"; sha="$3"
  tb="$(tarball_name "$ETVER" "$variant" "$platform")"
  printf 'set(ET_RUNTIME_URL_%s_%s\n  "%s/%s")\n' "$variant" "$platform" "$BASEURL" "$tb"
  printf 'set(ET_RUNTIME_SHA256_%s_%s "%s")\n\n' "$variant" "$platform" "$sha"
done
