#!/usr/bin/env bash
# Regenerate the OpenVINO requirements files from the scripts/lib/openvino.sh SSOT.
#   scripts/gen-requirements.sh           # write requirements/openvino-*.in
#   scripts/gen-requirements.sh --check   # exit 1 if the committed files are stale
#
# Why generated rather than hand-written: openvino.sh already pins OV_VERSION for the vendored
# runtime bundle (contract C10). A requirements file that spelled the version a second time could
# drift from it, and the failure would be near-invisible - fixtures exported against one OpenVINO
# and replayed against another usually still load. Generating removes the second spelling.
#
# test/requirements_ssot.test.sh runs --check in the hermetic suite, so a bumped OV_VERSION with
# stale requirements fails on the PR rather than in a release.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=lib/openvino.sh
. "$ROOT/scripts/lib/openvino.sh"

check=0
[ "${1:-}" = "--check" ] && check=1

gen() { # gen <basename> <body...>
  local name="$1"; shift
  printf '# GENERATED by scripts/gen-requirements.sh from scripts/lib/openvino.sh - DO NOT EDIT.\n'
  printf '# Regenerate with: scripts/gen-requirements.sh, then scripts/compile-requirements.sh\n'
  printf '%s\n' "$@"
  : "$name"
}

runtime_body=(
  ""
  "# Reading a compiled blob + building the fixture input (test/openvino/make_blob.py) needs the"
  "# python wheel at the SAME version as the vendored bundle under test."
  "openvino==${OV_VERSION}"
)
aot_body=(
  ""
  "# The ExecuTorch OpenVINO partitioner imports openvino.frontend.pytorch at module scope, so the"
  "# wheel is a hard import dependency of the export - not just a runtime concern."
  "openvino==${OV_VERSION}"
  "nncf==${OV_NNCF_VERSION}"
)

emit_runtime() { gen openvino-runtime "${runtime_body[@]}"; }
emit_aot()     { gen openvino-aot "${aot_body[@]}"; }

fail=0
write_or_check() { # write_or_check <path> <emitter>
  local path="$1" emitter="$2" want
  want="$("$emitter")"
  if [ "$check" -eq 1 ]; then
    if [ ! -f "$path" ] || [ "$want" != "$(cat "$path")" ]; then
      echo "STALE: $path does not match scripts/lib/openvino.sh (run scripts/gen-requirements.sh)" >&2
      fail=1
    fi
  else
    printf '%s\n' "$want" > "$path"
    echo "wrote $path"
  fi
}

mkdir -p "$ROOT/requirements"
write_or_check "$ROOT/requirements/openvino-runtime.in" emit_runtime
write_or_check "$ROOT/requirements/openvino-aot.in" emit_aot
exit "$fail"
